### ISSUE TITLE
RTL and LTR on same String value

### ISSUE THREAD

**Issue by DidarSeyidov** [ryanlintott/FrameUp#14]
Hi, I have long String value, that contains both RTL and LTR strings. To use environment layout modifier is not solve my problem, How can I achieve both types are aligned properly. I would appreciate if you give me some solution

**Comment by ryanlintott** [comment]
I see what you mean. HairSpaceJustifiedText was not handling mixed RTL and LTR text correctly as the text was broken down into lines and separated by a newline character "\n".  This break likely messed up the continuity of mixed LTR and RTL text. I've changed it so that it instead uses a space. This means the SwiftUI Text will wrap to newline on its own and the text will flow correctly. This should be in 0.9.4.
